// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkjaxbfspnrvkyruakyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpramF4YmZzcG5ydmt5cnVha3liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MTExMDksImV4cCI6MjA1ODQ4NzEwOX0.dpqguJNycQYC6v8S2et87RgcoKmvz-wJV0GzgRn_kv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);